version: '3.9'

services:
    db:
       image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
       environment:
         - ACCEPT_EULA=Y
         - MSSQL_SA_PASSWORD=1234@85231v.
         - MSSQL_PID=Evaluation
       ports:
         - "1433:1433"
       container_name: sqlpreview
       restart: always    
       healthcheck:
           test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "1234@85231v.", "-Q", "SELECT 1" ]
           interval: 10s
           timeout: 5s
           retries: 3
    db-init:
       image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
       network_mode: service:db
       command: bash -c 'until /opt/mssql-tools/bin/sqlcmd -U sa -P 1234@85231v. -Q "CREATE DATABASE Todo"; do echo retry && sleep 1; done'
       depends_on:
          db: 
            condition: service_healthy
    web:
        build: 
           context: .
           dockerfile: Dockerfile
        depends_on:
           db-init: 
              condition: service_completed_successfully
        ports:
        - "5000:8080"
